name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: SCP Files
      uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        source: "."
        target: ${{ secrets.SERVER_PATH }}
        key: ${{ secrets.KEY }}
        overwrite: true
